server:
  port: 8081

spring:
  application:
    name: USER-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
  
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/hotel_management_microservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # profiles:
  #   active: prod

  config:
    import: configserver:http://localhost:8085

  
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimunNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10